apiVersion: v1
kind: Namespace
metadata:
  name: cp4d-install
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: cpd-install-variables
  namespace: cp4d-install
immutable: false
data:
  OCP_URL: ""
  OPENSHIFT_TYPE: "self-managed"
  OCP_USERNAME: ""
  OCP_PASSWORD: ""
  #OCP_TOKEN: ""
  IMAGE_ARCH: "amd64"
  IBM_ENTITLEMENT_KEY: ""
  PROJECT_CPD_INST_OPERANDS: "cp4d"
  PROJECT_CPD_INST_OPERATORS: "cp4d-operators"
  PROJECT_SCHEDULING_SERVICE: "ibm-cpd-scheduler"
  PROJECT_LICENSE_SERVICE: "ibm-licensing"
  PROJECT_CERT_MANAGE: "ibm-cert-manager"
  STG_CLASS_FILE: "ocs-storagecluster-cephfs"
  STG_CLASS_BLOCK: "ocs-storagecluster-ceph-rbd"
  VERSION: "4.8.5"
  COMPONENTS: "ibm-cert-manager,ibm-licensing,scheduler,cpfs,cpd_platform"
  PODMAN_IGNORE_CGROUPSV1_WARNING: "true"
  COMMAND: "install"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: install-options
  namespace: cp4d-install
immutable: false
data:
  install-options.yml: |
    ################################################################################
    # Analytics Engine powered by Apache Spark parameters
    ################################################################################

    # ------------------------------------------------------------------------------
    # Analytics Engine powered by Apache Spark service configuration parameters
    # ------------------------------------------------------------------------------
    analyticsengine_spark_adv_enabled: true
    #analyticsengine_job_auto_delete_enabled: true
    #analyticsengine_kernel_cull_time: 30
    #analyticsengine_image_pull_parallelism: "40"
    #analyticsengine_image_pull_completions: "20"
    #analyticsengine_kernel_cleanup_schedule: "*/30 * * * *"
    #analyticsengine_job_cleanup_schedule: "*/30 * * * *"
    #analyticsengine_skip_selinux_relabeling: false
    #analyticsengine_mount_customizations_from_cchome: false

    # ------------------------------------------------------------------------------
    # Spark runtime configuration parameters
    # ------------------------------------------------------------------------------
    #analyticsengine_max_driver_cpu_cores: 5          # The number of CPUs to allocate to the Spark jobs driver. The default is 5.  
    #analyticsengine_max_executor_cpu_cores: 5        # The number of CPUs to allocate to the Spark jobs executor. The default is 5.
    #analyticsengine_max_driver_memory: "50g"         # The amount of memory, in gigabytes to allocate to the driver. The default is 50g.
    #analyticsengine_max_executor_memory: "50g"       # The amount of memory, in gigabytes to allocate to the executor. The default is 50g. 
    #analyticsengine_max_num_workers: 50              # The number of workers (also called executors) to allocate to spark jobs. The default is 50.
    #analyticsengine_local_dir_scale_factor: 10       # The number that is used to calculate the temporary disk size on Spark nodes. The formula is temp_disk_size = number_of_cpu * local_dir_scale_factor. The default is 10.
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cp4d-install-account
  namespace: cp4d-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cp4d-install-account-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cp4d-install-account
    namespace: cp4d-install
---
apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: cp4d-pidslimit-kubeletconfig
spec:
  kubeletConfig:
    podPidsLimit: 16384
  machineConfigPoolSelector:
    matchExpressions:
    - key: pools.operator.machineconfiguration.openshift.io/worker
      operator: Exists
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cpd-installer
  namespace: cp4d-install
spec:
  template:
    spec:
      serviceAccountName: cp4d-install-account
      containers:
        - name: cpd-installer
          image: quay.io/skol/cpd-installer:v4.8.5
          command: [ "ansible-playbook", "-v", "playbook/$(COMMAND).yml" ]
          securityContext:
            privileged: true
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: cpd-install-variables
          volumeMounts:
          - name: install-options-vol
            mountPath: /home/podman/playbook/cpd-cli-workspace/olm-utils-workspace/work/install-options.yml
            subPath: install-options.yml
            readOnly: false
      restartPolicy: Never
      volumes: 
        - name: install-options-vol
          configMap:
            name: install-options
            items:
              - key: install-options.yml
                path: install-options.yml
            defaultMode: 0777
  backoffLimit: 4
